version: '3.8'

services:
  api:
    image: ${TRANSPARENCIA_API_IMAGE}
    container_name: api
    ports:
      - "${TRANSPARENCIA_API_PORT}:8880"
    networks:
      - app-network
    env_file:
      - ./transparencia/api/.env

  frontend:
    image: ${TRANSPARENCIA_FRONTEND_IMAGE}
    container_name: frontend
    networks:
      - app-network
    volumes:
      - ./transparencia/frontend/dist:/app/dist
    command: ["npm", "run", "build"]
    env_file:
      - ./transparencia/frontend/.env
    depends_on:
      - api

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "${TRANSPARENCIA_FRONTEND_PORT}:80"
      #- "443:443"
    volumes:
      - ./transparencia/frontend/dist:/usr/share/nginx/html/transparencia
      - ./nginx/nginx-no-ssl.conf:/etc/nginx/nginx.conf
      #- ./nginx/nginx.conf:/etc/nginx/nginx.conf
      #- ./nginx/ssl:/etc/nginx/ssl  # Certificados SSL
    depends_on:
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge